### ISSUE TITLE
WAFv2 IPSet (dcv-portal-dev-frontend-ip-allowed): WAFInvalidParameterException: Error reason: The parameter contains formatting that is not valid., field: IP_ADDRESS, parameter: 0.0.0.0/0

### ISSUE THREAD

**Issue by adadouche** [aws-samples/dcv-web-portal#10]
Receiving the following error when deploying the content:

│ Error: creating WAFv2 IPSet (dcv-portal-dev-frontend-ip-allowed): WAFInvalidParameterException: Error reason: The parameter contains formatting that is not valid., field: IP_ADDRESS, parameter: 0.0.0.0/0
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "682f5dcb-fc28-4266-9dd5-71ddcb232c21"
│   },
│   Field: "IP_ADDRESS",
│   Message_: "Error reason: The parameter contains formatting that is not valid., field: IP_ADDRESS, parameter: 0.0.0.0/0",
│   Parameter: "0.0.0.0/0",
│   Reason: "The parameter contains formatting that is not valid."
│ }
│ 
│   with module.frontend.aws_wafv2_ip_set.frontend_waf_ip_allow_list,
│   on modules/frontend/main.tf line 61, in resource "aws_wafv2_ip_set" "frontend_waf_ip_allow_list":
│   61: resource "aws_wafv2_ip_set" "frontend_waf_ip_allow_list" {
│ 
╵

**Comment by ginodecock** [comment]
Hi,

I have the exact same error.

**Comment by jeromevdl** [comment]
Please, make sur to read the doc: https://github.com/aws-samples/dcv-web-portal#variablestf

You need to configure this.

**Comment by ginodecock** [comment]
Thx, that solves that
