### ISSUE TITLE
"InvalidClientTokenId: The security token included in the request is invalid" when deploying from Cloud9

### ISSUE THREAD

**Issue by adadouche** [aws-samples/dcv-web-portal#9]
When deploying the solution from Cloud9 with "AWS Managed Temporary credentials", I'm receiving the following error: 
```InvalidClientTokenId:` The security token included in the request is invalid```

I have added the PowerUserAccess and IAMFullAccess to the AWSCloud9SSMAccessRole.

I had to disable the  Cloud9 "AWS Managed Temporary credentials" feature and use an access key with ```aws configure``` to make it work.

**Comment by jeromevdl** [comment]
Thanks for your message. This is a Cloud9 "issue" (actually not an issue but behaviour). Nothing I can do on our side in this project. Thanks for your understanding.

**Comment by adadouche** [comment]
Could you at least document that Cloud9 will cause the behaviour?
